import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1774516165547 implements MigrationInterface {
    name = 'Migration1774516165547'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tb_user_profile\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`user_id\` int NOT NULL COMMENT 'User id', \`avatarUrl\` varchar(255) NULL COMMENT 'Avatar URL', \`coverUrl\` varchar(255) NULL COMMENT 'Cover/banner URL', \`bio\` text NULL COMMENT 'Bio', \`dateOfBirth\` date NULL COMMENT 'Date of birth', \`phone\` varchar(20) NULL COMMENT 'Phone number', \`fullAddress\` varchar(255) NOT NULL COMMENT 'Địa chỉ chi tiết', \`userWard\` varchar(255) NULL COMMENT 'Phường | xã', \`userDistrict\` varchar(255) NULL COMMENT 'Quận | huyện', \`userCity\` varchar(255) NULL COMMENT 'Thành Phố', \`userProvince\` varchar(255) NULL COMMENT 'Tỉnh', \`userCountry\` varchar(255) NULL COMMENT 'Quốc gia', \`userPortal\` varchar(255) NULL COMMENT 'Mã bưu chính', \`userLat\` varchar(255) NULL COMMENT 'Vĩ độ', \`userLong\` varchar(255) NULL COMMENT 'Kinh độ', \`userDescription\` varchar(255) NULL COMMENT 'Mô tả', \`userNote\` varchar(255) NULL COMMENT 'Ghi chú', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_service\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`serviceCode\` varchar(50) NOT NULL, \`serviceName\` varchar(100) NOT NULL, \`serviceDescription\` varchar(2000) NOT NULL, \`serviceLogo\` varchar(2000) NULL, \`serviceBackGround\` varchar(2000) NULL, \`servicePrice\` decimal NULL, \`serviceDiscount\` tinyint NULL, UNIQUE INDEX \`IDX_179cc521d0f44ae4469f41841d\` (\`serviceCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_user_default\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`username\` varchar(50) NOT NULL COMMENT 'Username', \`userCode\` varchar(50) NOT NULL COMMENT 'UserCode', \`email\` varchar(100) NOT NULL COMMENT 'User email', \`password\` varchar(255) NOT NULL COMMENT 'Hashed password', \`fullName\` varchar(100) NULL COMMENT 'Full name', \`status\` enum ('0', '1', '2') NOT NULL COMMENT 'User status' DEFAULT '0', \`role\` enum ('0', '1', '2') NOT NULL COMMENT 'User role' DEFAULT '2', \`isEmailVerified\` tinyint NOT NULL COMMENT 'Is email verified' DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_location-type\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`typeCode\` varchar(50) NOT NULL, \`typeName\` varchar(50) NOT NULL, \`typeDescription\` varchar(2000) NULL, \`typeLogo\` varchar(2000) NULL, \`typeBackGround\` varchar(2000) NULL, UNIQUE INDEX \`IDX_72815d2ec80bb2e76a878d6537\` (\`typeCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_location-service\` (\`locationCode\` varchar(50) NOT NULL, \`serviceCode\` varchar(50) NOT NULL, PRIMARY KEY (\`locationCode\`, \`serviceCode\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_location\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`typeCode\` varchar(50) NOT NULL, \`locationName\` varchar(100) NOT NULL, \`locationLogo\` varchar(250) NOT NULL, \`ownerCode\` varchar(100) NOT NULL, \`locationCode\` varchar(25) NOT NULL, \`minTimeLimit\` varchar(255) NULL, \`maxTimeLimit\` varchar(255) NULL, \`locationPriceStart\` decimal NULL, \`locationPriceEnd\` decimal NULL, \`locationPriceAfterDeal\` decimal NULL, \`hasRent\` int NULL, \`userRentCd\` varchar(50) NULL, \`locationDescription\` varchar(2000) NULL, \`locationNote\` varchar(2000) NULL, \`locationStatus\` int NOT NULL, \`locationRate\` int NULL, UNIQUE INDEX \`IDX_dde3994d7d03af926c306b6c46\` (\`locationCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_location-media\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`mediaCode\` varchar(50) NOT NULL, \`locationCode\` varchar(25) NOT NULL, \`mediaUrl\` varchar(2000) NOT NULL, \`mediaType\` enum ('IMAGE', 'VIDEO') NOT NULL DEFAULT 'IMAGE', \`displayOrder\` int NOT NULL DEFAULT '1', \`isLogo\` tinyint NOT NULL DEFAULT '0', \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4b2a74f08b34bdb7a01b896983\` (\`mediaCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_location-favorite\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`locationCode\` varchar(50) NOT NULL, \`userCode\` varchar(50) NOT NULL, UNIQUE INDEX \`IDX_location_favorite_location_user\` (\`locationCode\`, \`userCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_location-address\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key', \`locationCode\` varchar(25) NOT NULL COMMENT 'Mã địa điểm', \`addressCode\` varchar(25) NOT NULL COMMENT 'Mã địa chỉ', \`addressName\` varchar(255) NOT NULL COMMENT 'Tên địa chỉ', \`fullAddress\` varchar(255) NOT NULL COMMENT 'Địa chỉ chi tiết', \`addressWard\` varchar(255) NOT NULL COMMENT 'Phường | xã', \`addressDistrict\` varchar(255) NOT NULL COMMENT 'Quận | huyện', \`addressCity\` varchar(255) NOT NULL COMMENT 'Thành Phố', \`addressProvince\` varchar(255) NOT NULL COMMENT 'Tỉnh', \`addressCountry\` varchar(255) NOT NULL COMMENT 'Quốc gia', \`addressPortal\` varchar(255) NOT NULL COMMENT 'Mã bưu chính', \`addressLat\` varchar(255) NOT NULL COMMENT 'Vĩ độ', \`addressLong\` varchar(255) NOT NULL COMMENT 'Kinh độ', \`addressRegion\` varchar(255) NOT NULL COMMENT 'Vùng', \`addressStatus\` varchar(255) NOT NULL COMMENT 'Trạng thái', \`addressDescription\` varchar(255) NOT NULL COMMENT 'Mô tả', \`addressNote\` varchar(255) NOT NULL COMMENT 'Ghi chú', \`addressType\` varchar(255) NOT NULL COMMENT 'Phân loại', UNIQUE INDEX \`IDX_f04b8a19e7ebb203771e55f01d\` (\`addressCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_message\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính của tin nhắn', \`conversationId\` int NOT NULL COMMENT 'ID cuộc trò chuyện chứa tin nhắn này', \`senderId\` int NOT NULL COMMENT 'ID người gửi tin nhắn', \`type\` enum ('TEXT', 'IMAGE', 'FILE', 'SYSTEM') NOT NULL COMMENT 'Loại tin nhắn: TEXT, IMAGE, FILE, SYSTEM' DEFAULT 'TEXT', \`content\` text NULL COMMENT 'Nội dung tin nhắn dạng văn bản', \`metadata\` json NULL COMMENT 'Dữ liệu bổ sung (ví dụ: imageUrl, fileUrl, kích thước, metadata...)', \`isDeleted\` tinyint NOT NULL COMMENT 'Trạng thái xóa tin nhắn (xóa cho tất cả thành viên)' DEFAULT 0, \`createdAt\` timestamp(6) NOT NULL COMMENT 'Thời điểm gửi tin nhắn' DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_df478b6f36c8fa434b020420d6\` (\`senderId\`), INDEX \`IDX_c2b1b017aa4470103f4790d855\` (\`conversationId\`, \`id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_conversation_participant\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính của bản ghi người tham gia cuộc trò chuyện', \`conversationId\` int NOT NULL COMMENT 'ID cuộc trò chuyện mà người dùng tham gia', \`userId\` int NOT NULL COMMENT 'ID người dùng tham gia cuộc trò chuyện', \`unreadCount\` int NOT NULL COMMENT 'Số lượng tin nhắn chưa đọc của người dùng trong cuộc trò chuyện' DEFAULT '0', \`lastReadMessageId\` bigint NULL COMMENT 'ID tin nhắn cuối cùng mà người dùng đã đọc', \`isMuted\` tinyint NOT NULL COMMENT 'Trạng thái tắt thông báo của người dùng đối với cuộc trò chuyện' DEFAULT 0, \`isPinned\` tinyint NOT NULL COMMENT 'Trạng thái ghim cuộc trò chuyện lên đầu danh sách' DEFAULT 0, \`isDeleted\` tinyint NOT NULL COMMENT 'Trạng thái ẩn/xóa cuộc trò chuyện phía người dùng (soft delete)' DEFAULT 0, INDEX \`IDX_a403e8f9bbf60f81880b998e7f\` (\`userId\`), UNIQUE INDEX \`IDX_a610f947b6b877960a9aa6116c\` (\`conversationId\`, \`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tb_conversation\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính của cuộc trò chuyện (định danh duy nhất)', \`type\` enum ('PRIVATE', 'GROUP') NOT NULL COMMENT 'Loại cuộc trò chuyện: PRIVATE (1-1) hoặc GROUP (nhóm)' DEFAULT 'PRIVATE', \`name\` varchar(255) NULL COMMENT 'Tên cuộc trò chuyện (chỉ dùng cho nhóm)', \`avatar\` varchar(255) NULL COMMENT 'Đường dẫn ảnh đại diện của cuộc trò chuyện (nhóm)', \`lastMessage\` varchar(255) NULL COMMENT 'Nội dung tin nhắn cuối cùng (lưu cache để load danh sách nhanh)', \`lastMessageAt\` timestamp NULL COMMENT 'Thời điểm gửi tin nhắn cuối cùng', \`createdAt\` timestamp(6) NOT NULL COMMENT 'Thời điểm tạo cuộc trò chuyện' DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL COMMENT 'Thời điểm cập nhật gần nhất (tự động cập nhật khi có thay đổi)' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tb_location-media\` ADD CONSTRAINT \`FK_07dc06cb2851d375665ba9e33f1\` FOREIGN KEY (\`locationCode\`) REFERENCES \`tb_location\`(\`locationCode\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tb_location-media\` DROP FOREIGN KEY \`FK_07dc06cb2851d375665ba9e33f1\``);
        await queryRunner.query(`DROP TABLE \`tb_conversation\``);
        await queryRunner.query(`DROP INDEX \`IDX_a610f947b6b877960a9aa6116c\` ON \`tb_conversation_participant\``);
        await queryRunner.query(`DROP INDEX \`IDX_a403e8f9bbf60f81880b998e7f\` ON \`tb_conversation_participant\``);
        await queryRunner.query(`DROP TABLE \`tb_conversation_participant\``);
        await queryRunner.query(`DROP INDEX \`IDX_c2b1b017aa4470103f4790d855\` ON \`tb_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_df478b6f36c8fa434b020420d6\` ON \`tb_message\``);
        await queryRunner.query(`DROP TABLE \`tb_message\``);
        await queryRunner.query(`DROP INDEX \`IDX_f04b8a19e7ebb203771e55f01d\` ON \`tb_location-address\``);
        await queryRunner.query(`DROP TABLE \`tb_location-address\``);
        await queryRunner.query(`DROP INDEX \`IDX_location_favorite_location_user\` ON \`tb_location-favorite\``);
        await queryRunner.query(`DROP TABLE \`tb_location-favorite\``);
        await queryRunner.query(`DROP INDEX \`IDX_4b2a74f08b34bdb7a01b896983\` ON \`tb_location-media\``);
        await queryRunner.query(`DROP TABLE \`tb_location-media\``);
        await queryRunner.query(`DROP INDEX \`IDX_dde3994d7d03af926c306b6c46\` ON \`tb_location\``);
        await queryRunner.query(`DROP TABLE \`tb_location\``);
        await queryRunner.query(`DROP TABLE \`tb_location-service\``);
        await queryRunner.query(`DROP INDEX \`IDX_72815d2ec80bb2e76a878d6537\` ON \`tb_location-type\``);
        await queryRunner.query(`DROP TABLE \`tb_location-type\``);
        await queryRunner.query(`DROP TABLE \`tb_user_default\``);
        await queryRunner.query(`DROP INDEX \`IDX_179cc521d0f44ae4469f41841d\` ON \`tb_service\``);
        await queryRunner.query(`DROP TABLE \`tb_service\``);
        await queryRunner.query(`DROP TABLE \`tb_user_profile\``);
    }

}
